version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./core:/core
      - ./core/staticfiles:/staticfiles
    ports:
      - "8000:8000"
    environment:
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - STRIPE_SECRET_KEY_EUR=${STRIPE_SECRET_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - STRIPE_SECRET_KEY_USD=${STRIPE_SECRET_KEY_USD}

  nginx:
    image: nginx:latest
    container_name: django_nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./core/staticfiles:/staticfiles